namespace MicroPlumberd;

/// <summary>
/// Attribute used to decorate dispatching method to list possible concrete types. It is when code gets generated by source generators.
/// </summary>
/// <seealso cref="System.Attribute" />
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true, Inherited = true)]
public class AcceptedTypeAttribute : Attribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="AcceptedTypeAttribute"/> class.
    /// </summary>
    /// <param name="acceptedType">The concrete type that the decorated method can accept.</param>
    public AcceptedTypeAttribute(Type acceptedType)
    {
        AcceptedType = acceptedType;
    }
    /// <summary>
    /// Gets or sets the accepted type of dispatching method.
    /// </summary>
    /// <value>
    /// The type that is accepted by dispatching method.
    /// </value>
    public Type AcceptedType { get; init; }
}