namespace MicroPlumberd.Services.Uniqueness;

/// <summary>PostgreSQL DDL and clock for a category's reservation table.</summary>
class PostgresUniquenessDialect : IUniquenessDialect
{
    public bool Handles(string providerName) => providerName == "Npgsql.EntityFrameworkCore.PostgreSQL";

    /// <summary>
    /// <c>clock_timestamp()</c> yields timestamptz, which Npgsql reads back as UTC regardless of the
    /// server's TimeZone setting — matching the timestamptz column ValidUntil is stored in.
    /// </summary>
    /// <remarks>
    /// Deliberately NOT <c>now()</c>: <c>now()</c> is <c>transaction_timestamp()</c>, so inside an explicit
    /// transaction it returns the instant the TRANSACTION began and never advances. A lease read that way
    /// would silently drift the longer the transaction ran, and the drift would be invisible until a long
    /// transaction mis-expired something. <c>clock_timestamp()</c> is the actual current instant, which is
    /// what the other dialects' expressions already return.
    /// </remarks>
    public string UtcNowSql => "clock_timestamp()";

    public IEnumerable<string> CreateSchema(string table)
    {
        yield return $"""
            CREATE TABLE IF NOT EXISTS "{table}" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                "Name" character varying(400) NOT NULL,
                "SourceId" uuid NOT NULL,
                "ValidUntil" timestamp with time zone NOT NULL,
                "IsConfirmed" boolean NOT NULL,
                CONSTRAINT "PK_{table}" PRIMARY KEY ("Id")
            )
            """;

        // The lock the whole pattern rests on.
        yield return $"""CREATE UNIQUE INDEX IF NOT EXISTS "IX_{table}_Name" ON "{table}" ("Name")""";
        yield return $"""CREATE INDEX IF NOT EXISTS "IX_{table}_SourceId" ON "{table}" ("SourceId")""";
    }
}
